name: 'Chat-App' 
on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku # set whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0 # use the latest version of the action
        with:
          email: 'suhaib.khalid@techverx.com' # your heroku email
          api_key: 'b0b8ef3b-93be-43b0-b2a8-417eb46f85ff' # your heroku api key
          app_name: 'system-210' # you aplication name
          dockerfile_path: 'D:\Docker Related\Heroku-Deploy\chat-app docker' # set the path to the folder where the Dockerfile is located
          options: '' # Docker Build Options
          formation: '' # Docker Dyno Formation. By default is web
